# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

target 'CapacitorZendeskChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CapacitorZendeskChat

  pod 'Capacitor'
  pod 'ZDCChat', '~> 1.4.7'

end
